/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cfilter_kernel_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* cfilter:(att[7],gyro[3],accel[3],alpha,dt)->(y0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
    a00=arg[3]? arg[3][0] : 0;
    a01=arg[0]? arg[0][0] : 0;
    a02=5.0000000000000000e-01;
    a03=arg[0]? arg[0][1] : 0;
    a04=arg[1]? arg[1][0] : 0;
    a05=(a03*a04);
    a06=arg[0]? arg[0][2] : 0;
    a07=arg[1]? arg[1][1] : 0;
    a08=(a06*a07);
    a05=(a05+a08);
    a08=arg[0]? arg[0][3] : 0;
    a09=arg[1]? arg[1][2] : 0;
    a10=(a08*a09);
    a05=(a05+a10);
    a05=(a02*a05);
    a10=arg[4]? arg[4][0] : 0;
    a05=(a05*a10);
    a05=(a01-a05);
    a11=casadi_sq(a05);
    a12=(a01*a04);
    a13=(a06*a09);
    a12=(a12+a13);
    a13=(a08*a07);
    a12=(a12-a13);
    a12=(a02*a12);
    a12=(a12*a10);
    a12=(a03+a12);
    a13=casadi_sq(a12);
    a11=(a11+a13);
    a13=(a01*a07);
    a14=(a03*a09);
    a13=(a13-a14);
    a14=(a08*a04);
    a13=(a13+a14);
    a13=(a02*a13);
    a13=(a13*a10);
    a13=(a06+a13);
    a14=casadi_sq(a13);
    a11=(a11+a14);
    a01=(a01*a09);
    a03=(a03*a07);
    a01=(a01+a03);
    a06=(a06*a04);
    a01=(a01-a06);
    a01=(a02*a01);
    a01=(a01*a10);
    a08=(a08+a01);
    a01=casadi_sq(a08);
    a11=(a11+a01);
    a11=sqrt(a11);
    a05=(a05/a11);
    a05=(a00*a05);
    a01=1.;
    a10=(a01-a00);
    a06=arg[2]? arg[2][1] : 0;
    a04=arg[2]? arg[2][0] : 0;
    a03=casadi_sq(a04);
    a07=casadi_sq(a06);
    a03=(a03+a07);
    a07=arg[2]? arg[2][2] : 0;
    a09=casadi_sq(a07);
    a03=(a03+a09);
    a03=sqrt(a03);
    a06=(a06/a03);
    a09=(-a06);
    a07=(a07/a03);
    a14=(-a07);
    a09=atan2(a09,a14);
    a14=(a02*a09);
    a14=cos(a14);
    a04=(a04/a03);
    a06=casadi_sq(a06);
    a07=casadi_sq(a07);
    a06=(a06+a07);
    a06=sqrt(a06);
    a04=atan2(a04,a06);
    a06=(a02*a04);
    a06=cos(a06);
    a07=(a14*a06);
    a03=arg[0]? arg[0][6] : 0;
    a15=(a02*a03);
    a15=cos(a15);
    a07=(a07*a15);
    a09=(a02*a09);
    a09=sin(a09);
    a04=(a02*a04);
    a04=sin(a04);
    a16=(a09*a04);
    a02=(a02*a03);
    a02=sin(a02);
    a16=(a16*a02);
    a07=(a07+a16);
    a16=casadi_sq(a07);
    a03=(a09*a06);
    a03=(a03*a15);
    a17=(a14*a04);
    a17=(a17*a02);
    a03=(a03-a17);
    a17=casadi_sq(a03);
    a16=(a16+a17);
    a17=(a14*a04);
    a17=(a17*a15);
    a18=(a09*a06);
    a18=(a18*a02);
    a17=(a17+a18);
    a18=casadi_sq(a17);
    a16=(a16+a18);
    a14=(a14*a06);
    a14=(a14*a02);
    a09=(a09*a04);
    a09=(a09*a15);
    a14=(a14-a09);
    a09=casadi_sq(a14);
    a16=(a16+a09);
    a16=sqrt(a16);
    a07=(a07/a16);
    a07=(a10*a07);
    a05=(a05+a07);
    if (res[0]!=0) res[0][0]=a05;
    a12=(a12/a11);
    a12=(a00*a12);
    a03=(a03/a16);
    a03=(a10*a03);
    a12=(a12+a03);
    if (res[0]!=0) res[0][1]=a12;
    a13=(a13/a11);
    a13=(a00*a13);
    a17=(a17/a16);
    a17=(a10*a17);
    a13=(a13+a17);
    if (res[0]!=0) res[0][2]=a13;
    a08=(a08/a11);
    a00=(a00*a08);
    a14=(a14/a16);
    a10=(a10*a14);
    a00=(a00+a10);
    if (res[0]!=0) res[0][3]=a00;
    a10=2.;
    a14=(a05*a12);
    a16=(a13*a00);
    a14=(a14+a16);
    a14=(a10*a14);
    a16=casadi_sq(a12);
    a08=casadi_sq(a13);
    a16=(a16+a08);
    a16=(a10*a16);
    a16=(a01-a16);
    a14=atan2(a14,a16);
    if (res[0]!=0) res[0][4]=a14;
    a14=(a05*a13);
    a16=(a00*a12);
    a14=(a14-a16);
    a14=(a10*a14);
    a16=casadi_fabs(a14);
    a16=(a01<=a16);
    a08=1.5707963267948966e+00;
    a11=casadi_sign(a14);
    a08=(a08*a11);
    a08=(a16?a08:0);
    a16=(!a16);
    a14=asin(a14);
    a16=(a16?a14:0);
    a08=(a08+a16);
    if (res[0]!=0) res[0][5]=a08;
    a05=(a05*a00);
    a12=(a12*a13);
    a05=(a05+a12);
    a05=(a10*a05);
    a13=casadi_sq(a13);
    a00=casadi_sq(a00);
    a13=(a13+a00);
    a10=(a10*a13);
    a01=(a01-a10);
    a05=atan2(a05,a01);
    if (res[0]!=0) res[0][6]=a05;
    return 0;
}

CASADI_SYMBOL_EXPORT int cfilter(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cfilter_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int cfilter_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void cfilter_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cfilter_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void cfilter_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cfilter_incref(void) {
}

CASADI_SYMBOL_EXPORT void cfilter_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cfilter_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cfilter_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cfilter_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* cfilter_name_in(casadi_int i) {
    switch (i) {
        case 0: return "att";
        case 1: return "gyro";
        case 2: return "accel";
        case 3: return "alpha";
        case 4: return "dt";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* cfilter_name_out(casadi_int i) {
    switch (i) {
        case 0: return "y0";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* cfilter_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s1;
        case 3: return casadi_s2;
        case 4: return casadi_s2;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* cfilter_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int cfilter_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 5;
    if (sz_res) *sz_res = 1;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

CASADI_SYMBOL_EXPORT int cfilter_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
    if (sz_res) *sz_res = 1*sizeof(casadi_real*);
    if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
    if (sz_w) *sz_w = 0*sizeof(casadi_real);
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
