name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: |
        uv sync --all-extras --dev
        python -m ipykernel install --user --name archimedes

    - name: Run tests
      run: uv run pytest --cov=archimedes --cov-report=xml

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true
    #     token: ${{ secrets.CODECOV_TOKEN }}

    - name: Test notebooks
      run: uv run pytest --nbmake docs/source/notebooks/*.ipynb

    - name: Lint with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .


  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          python-version: 3.12

    - name: Install the project
      run: |
        uv sync --all-extras --dev
        python -m ipykernel install --user --name archimedes

    - name: Build documentation
      run: |
        cd docs
        make nbconvert
        make html
  